// Initial criteria configuration for build lists page
import type { ListCriteria } from '@/types/list-builder';

// Factory function that computes currentYear at call time
export function createInitialCriteria(options?: { enableSensitiveCriteria?: boolean }): ListCriteria {
  const currentYear = new Date().getFullYear();
  const enableSensitiveCriteria = options?.enableSensitiveCriteria ?? 
    process.env.NEXT_PUBLIC_ENABLE_SENSITIVE_CRITERIA === 'true';

  return {
    geography: {
      states: [],
      zipCodes: [],
      cities: [],
      counties: [],
      areaCodes: [],
      censusTract: [],
      fipsCodes: [],
      msa: [],
      mapBookPage: [],
      mapSearch: [],
      municipality: [],
      parcelIdRange: [],
      scf: [],
      streetName: [],
      subdivision: [],
      taxRateArea: [],
      townshipRangeSection: [],
      tract: [],
      zipRadius: [],
      selectedCriteria: [],
    },
    property: {
      propertyTypes: [],
      yearBuilt: [1900, currentYear],
      squareFootage: [500, 10000],
      bedrooms: [1, 8],
      bathrooms: [1, 8],
      lotSize: [0.1, 10],
      propertyValue: [50000, 2000000],
    },
    demographics: {
      selectedCriteria: [],
      age: [18, 100],
      gender: [],
      maritalStatus: [],
      householdSize: [1, 8],
      income: [25000, 250000],
      educationLevel: [],
      occupation: [],
      employmentStatus: [],
      homeOwnership: [],
      creditRating: [],
      lifestyle: {
        interests: [],
        hobbies: [],
        purchasingBehavior: [],
      },
      ...(enableSensitiveCriteria && {
        ethnicity: [],
        language: [],
        religion: [],
        politicalAffiliation: [],
        veteranStatus: [],
      }),
      childrenInHousehold: {
        hasChildren: 'any',
        ageRanges: [],
        numberOfChildren: [0, 5],
      },
      lienPosition: ALL,
      selectedCriteria: [],
      mortgageAmount: null,
      interestRate: null,
      loanToValue: null,
      mortgageOriginationDate: null,
      maturityDate: null,
      mortgageTerm: [],
      primaryLoanType: [],
      lenderOrigination: [],
      lenderAssigned: [],
      adjustableRateRider: {
        selectedSubCriteria: null,
        interestOnly: NO_PREF,
        interestRateChangeLimit: [],
        interestRateChange: [],
        interestRateChangeDate: { type: 'initial', dates: [] },
        interestRateChangeFrequency: [],
        interestRateIndexType: [],
        interestRateMaximum: [],
        negativeAmortization: NO_PREF,
        paymentOption: NO_PREF,
        prepaymentPenalty: NO_PREF,
        prepaymentPenaltyExpireDate: [],
      },
      balloonLoan: NO_PREF,
      creditLineLoan: NO_PREF,
      equityLoan: NO_PREF,
      maturedMortgage: NO_PREF,
      creditLineLoan: 'no-preference',
      equityLoan: 'no-preference',
      maturedMortgage: 'no-preference',
    },
    foreclosure: {
      selectedCriteria: [],
      foreclosureStatus: [],
      foreclosureDate: null,
      foreclosureAmount: null,
      lenderNames: [],
      currentOwners: [],
      propertyAddresses: [],
      auctionDate: null,
      noticeTypes: [],
      trusteeNames: [],
      caseNumbers: [],
    },
    predictive: {
      selectedModel: null,
      modelScores: {},
      selectedCriteria: [],
    },
    options: {
      selectedCriteria: [],
      listCleaning: {
        removeDuplicates: false,
        removeDeceased: false,
        removePrisonersInmates: false,
        removeBusinesses: false,
        removeVacantProperties: false,
      },
      dataQuality: {
        requirePhoneNumbers: false,
        requireEmailAddresses: false,
        requireCompleteAddresses: false,
        minimumConfidenceScore: 50,
      },
      deliveryPreferences: {
        excludePoBoxes: false,
        excludeApartments: false,
        excludeCondos: false,
        excludeMobileHomes: false,
        requireCarrierRoute: false,
      },
      suppressionLists: {
        nationalDoNotMail: false,
        customSuppressionList: [],
        previousMailings: false,
        competitors: false,
      },
      dataFreshness: {
        maxAge: 12,
        requireRecentUpdate: false,
      },
      additionalData: {
        appendPhoneNumbers: false,
        appendEmailAddresses: false,
        appendPropertyDetails: false,
        appendDemographics: false,
        appendLifestyleData: false,
      },
      exportOptions: {
        format: 'csv',
        includeHeaders: true,
        sortBy: 'address',
        maxRecordsPerFile: 10000,
      },
    },
  };
}

// Convenience constant for backward compatibility
export const initialCriteria: ListCriteria = createInitialCriteria();
