// Complete list of all 50 US states
export const US_STATES = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
]

export const GEOGRAPHY_CRITERIA_OPTIONS = [
  { value: 'state', label: 'State', description: 'Select one or multiple states' },
  { value: 'area-code', label: 'Area Code', description: 'Target properties by telephone area code' },
  { value: 'census-tract', label: 'Census Tract', description: 'Filter by census tract numbers' },
  { value: 'city', label: 'City', description: 'Select specific cities within states' },
  { value: 'county', label: 'County', description: 'Filter by county boundaries' },
  { value: 'fips-code', label: 'FIPS Code', description: 'Federal Information Processing Standard codes' },
  { value: 'msa', label: 'MSA (Metropolitan Statistical Area)', description: 'Metropolitan statistical areas' },
  { value: 'map-book-page', label: 'Map Book Page/Grid', description: 'Local map book references' },
  { value: 'map-search', label: 'Map Search', description: 'Interactive map selection with custom shapes' },
  { value: 'municipality', label: 'Municipality/Township', description: 'Municipal and township boundaries' },
  { value: 'parcel-id', label: 'Parcel ID Range', description: 'Property parcel identification ranges' },
  { value: 'scf', label: 'SCF (Sectional Center Facility)', description: 'First three digits of ZIP codes' },
  { value: 'street-name', label: 'Street Name', description: 'Specific street segments with house numbers' },
  { value: 'subdivision', label: 'Subdivision', description: 'Named subdivisions and developments' },
  { value: 'tax-rate-area', label: 'Tax Rate Area', description: 'Tax millage code areas' },
  { value: 'trs', label: 'Township-Range-Section (TRS)', description: 'Public Land Survey System coordinates' },
  { value: 'tract', label: 'Tract', description: 'Local tract numbers' },
  { value: 'zip-radius', label: 'ZIP + Radius', description: 'ZIP code with radius in miles' },
  { value: 'zip-code', label: 'ZIP Code', description: 'Specific ZIP codes or ranges' },
]